 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package book4fun;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Map;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
/**
 *
 * @author gesto
 */
public class CreacionAlquiler extends javax.swing.JFrame {

    public boolean entrado = true;
    public int creditos;
    public CreacionAlquiler() {
        initComponents();
        
        creditos = BD.comprobarUsuario().getCreditos();
        nCreditos.setText(String.valueOf(creditos));

        panelCreditos.setVisible(false);
        panelNoTransRealizada.setVisible(false);
        panelTransRealizada.setVisible(false);
        panelNoPosible.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_General = new javax.swing.JPanel();
        panelCreditos = new javax.swing.JPanel();
        panelTransRealizada = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        panelNoPosible = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        panelNoTransRealizada = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        boton100 = new javax.swing.JButton();
        inputDinero = new javax.swing.JTextField();
        txtIngresarDinero = new javax.swing.JLabel();
        boton30 = new javax.swing.JButton();
        boton50 = new javax.swing.JButton();
        boton10 = new javax.swing.JButton();
        transferencia = new javax.swing.JButton();
        SideBar = new javax.swing.JPanel();
        lista = new javax.swing.JLabel();
        favoritos = new javax.swing.JLabel();
        buscador1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        botonCreditos = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        nCreditos1 = new javax.swing.JLabel();
        nCreditos = new javax.swing.JLabel();
        Raya_verde1 = new javax.swing.JPanel();
        filtro = new javax.swing.JPanel();
        registro = new javax.swing.JPanel();
        registro1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tipoAlquiler = new javax.swing.JTextField();
        precioAlquilerDia = new javax.swing.JTextField();
        direccionAlquiler = new javax.swing.JTextField();
        nombreDueñoAlquiler = new javax.swing.JTextField();
        localizacionAlquiler = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        metrosAlquiler = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        habitacionesAlquiler = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        nombreAlquiler = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        crearAlquiler = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        bañosAlquiler = new javax.swing.JTextField();
        wifiAlquiler = new javax.swing.JCheckBox();
        piscinaAlquiler = new javax.swing.JCheckBox();
        imagen = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel_General.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelCreditos.setBackground(new java.awt.Color(33, 40, 42));
        panelCreditos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(139, 195, 73)));
        panelCreditos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelTransRealizada.setBackground(new java.awt.Color(255, 201, 14));
        panelTransRealizada.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel5.setText("realizada ");
        panelTransRealizada.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 99, -1, 131));

        jLabel19.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel19.setText("Transeferencia ");
        panelTransRealizada.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 16, -1, 131));

        jButton2.setBackground(new java.awt.Color(33, 40, 42));
        jButton2.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(139, 195, 73));
        jButton2.setText("Completar");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(139, 195, 73), 2));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panelTransRealizada.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 236, 186, 75));

        panelCreditos.add(panelTransRealizada, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 430, 360));

        panelNoPosible.setBackground(new java.awt.Color(255, 201, 14));
        panelNoPosible.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel22.setText("entre 10");
        panelNoPosible.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 153, -1, 42));

        jLabel23.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel23.setText("Los numero tienen");
        panelNoPosible.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 22, 397, 65));

        jButton4.setBackground(new java.awt.Color(33, 40, 42));
        jButton4.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(139, 195, 73));
        jButton4.setText("Cerrar");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(139, 195, 73), 2));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        panelNoPosible.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 262, 186, 75));

        jLabel24.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel24.setText("que ser divisibles ");
        panelNoPosible.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 93, -1, 42));

        panelCreditos.add(panelNoPosible, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 430, 360));

        panelNoTransRealizada.setBackground(new java.awt.Color(255, 201, 14));
        panelNoTransRealizada.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel20.setText("realizada ");
        panelNoTransRealizada.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 143, -1, 78));

        jButton3.setBackground(new java.awt.Color(33, 40, 42));
        jButton3.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(139, 195, 73));
        jButton3.setText("Cerrar");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(139, 195, 73), 2));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        panelNoTransRealizada.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 248, 186, 75));

        jLabel21.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel21.setText("Transaccion no");
        panelNoTransRealizada.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 47, 339, 78));

        panelCreditos.add(panelNoTransRealizada, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 430, 360));

        boton100.setFont(new java.awt.Font("Arial Black", 0, 20)); // NOI18N
        boton100.setText("100€");
        boton100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton100ActionPerformed(evt);
            }
        });
        panelCreditos.add(boton100, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 56, 85, 85));

        inputDinero.setToolTipText("");
        inputDinero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputDineroActionPerformed(evt);
            }
        });
        panelCreditos.add(inputDinero, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 230, 394, 52));

        txtIngresarDinero.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtIngresarDinero.setForeground(new java.awt.Color(139, 195, 73));
        txtIngresarDinero.setText("Ingresa el dinero que quieras cambiar:");
        panelCreditos.add(txtIngresarDinero, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 190, 373, 34));

        boton30.setFont(new java.awt.Font("Arial Black", 0, 25)); // NOI18N
        boton30.setText("30€");
        boton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton30ActionPerformed(evt);
            }
        });
        panelCreditos.add(boton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 56, 85, 85));

        boton50.setFont(new java.awt.Font("Arial Black", 0, 25)); // NOI18N
        boton50.setText("50€");
        boton50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton50ActionPerformed(evt);
            }
        });
        panelCreditos.add(boton50, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 56, 85, 85));

        boton10.setFont(new java.awt.Font("Arial Black", 0, 25)); // NOI18N
        boton10.setText("10€");
        boton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton10ActionPerformed(evt);
            }
        });
        panelCreditos.add(boton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 56, 85, 85));

        transferencia.setBackground(new java.awt.Color(33, 40, 42));
        transferencia.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        transferencia.setForeground(new java.awt.Color(139, 195, 73));
        transferencia.setText("Completar Transferencia");
        transferencia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(139, 195, 73), 2));
        transferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferenciaActionPerformed(evt);
            }
        });
        panelCreditos.add(transferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 300, 175, 56));

        Panel_General.add(panelCreditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 450, 390));

        SideBar.setBackground(new java.awt.Color(33, 40, 42));
        SideBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/book4fun/imagenes/lista2.PNG"))); // NOI18N
        lista.setText("jLabel2");
        lista.setMaximumSize(new java.awt.Dimension(40, 40));
        lista.setMinimumSize(new java.awt.Dimension(40, 40));
        SideBar.add(lista, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 50, 50));

        favoritos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/book4fun/imagenes/historial.PNG"))); // NOI18N
        favoritos.setText("jLabel2");
        favoritos.setMaximumSize(new java.awt.Dimension(40, 40));
        favoritos.setMinimumSize(new java.awt.Dimension(40, 40));
        SideBar.add(favoritos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 50, 50));

        buscador1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/book4fun/imagenes/buscador.PNG"))); // NOI18N
        buscador1.setText("buscador");
        buscador1.setMaximumSize(new java.awt.Dimension(40, 40));
        buscador1.setMinimumSize(new java.awt.Dimension(40, 40));
        SideBar.add(buscador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 50, 50));

        jButton1.setBackground(new java.awt.Color(33, 40, 42));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/book4fun/imagenes/profile.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        SideBar.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        botonCreditos.setBackground(new java.awt.Color(139, 195, 73));
        botonCreditos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/book4fun/imagenes/iconoCredito.png"))); // NOI18N
        botonCreditos.setBorderPainted(false);
        botonCreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCreditosActionPerformed(evt);
            }
        });
        SideBar.add(botonCreditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 70, 60));

        jPanel6.setBackground(new java.awt.Color(139, 195, 73));

        nCreditos1.setBackground(new java.awt.Color(139, 195, 73));
        nCreditos1.setText("Creditos:");
        nCreditos1.setToolTipText("");
        nCreditos1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nCreditos1.setInheritsPopupMenu(false);

        nCreditos.setBackground(new java.awt.Color(139, 195, 73));
        nCreditos.setText("n");
        nCreditos.setToolTipText("");
        nCreditos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nCreditos.setInheritsPopupMenu(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nCreditos1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(nCreditos1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SideBar.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 70, 50));

        Panel_General.add(SideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 100, 1070));

        Raya_verde1.setBackground(new java.awt.Color(139, 195, 73));

        javax.swing.GroupLayout Raya_verde1Layout = new javax.swing.GroupLayout(Raya_verde1);
        Raya_verde1.setLayout(Raya_verde1Layout);
        Raya_verde1Layout.setHorizontalGroup(
            Raya_verde1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Raya_verde1Layout.setVerticalGroup(
            Raya_verde1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );

        Panel_General.add(Raya_verde1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 1, -1));

        filtro.setBackground(new java.awt.Color(139, 195, 73));

        javax.swing.GroupLayout filtroLayout = new javax.swing.GroupLayout(filtro);
        filtro.setLayout(filtroLayout);
        filtroLayout.setHorizontalGroup(
            filtroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1820, Short.MAX_VALUE)
        );
        filtroLayout.setVerticalGroup(
            filtroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        Panel_General.add(filtro, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 1820, 70));

        registro.setBackground(new java.awt.Color(33, 40, 42));
        registro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registro1.setBackground(new java.awt.Color(33, 40, 42));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 306, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 528, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 294, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout registro1Layout = new javax.swing.GroupLayout(registro1);
        registro1.setLayout(registro1Layout);
        registro1Layout.setHorizontalGroup(
            registro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registro1Layout.createSequentialGroup()
                .addGap(1124, 1124, 1124)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(187, Short.MAX_VALUE))
        );
        registro1Layout.setVerticalGroup(
            registro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registro1Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(registro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        registro.add(registro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1984, 227, -1, -1));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        jPanel11.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 510, 320));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("i se generara un precio automatico que varia segun la cantidad de dias seleccionado");
        jPanel11.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 570, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel4.setText("Precio por dia:");
        jPanel11.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel6.setText("Tipo:");
        jPanel11.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 350, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel7.setText("Nombre dueño:");
        jPanel11.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 140, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel8.setText("Nombre dueño:");
        jPanel11.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 140, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel10.setText("Localizacion:");
        jPanel11.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 170, -1, -1));

        tipoAlquiler.setText("jTextField1");
        jPanel11.add(tipoAlquiler, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 350, 220, -1));

        precioAlquilerDia.setText("jTextField1");
        jPanel11.add(precioAlquilerDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, 310, 40));

        direccionAlquiler.setText("jTextField1");
        jPanel11.add(direccionAlquiler, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 100, 220, 30));

        nombreDueñoAlquiler.setText("jTextField1");
        jPanel11.add(nombreDueñoAlquiler, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 140, 220, -1));

        localizacionAlquiler.setText("jTextField1");
        jPanel11.add(localizacionAlquiler, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 170, 220, -1));

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel9.setText("Metros cuadrados:");
        jPanel11.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 200, -1, -1));

        metrosAlquiler.setText("jTextField1");
        jPanel11.add(metrosAlquiler, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 200, 220, -1));

        jLabel11.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel11.setText("Piscina:");
        jPanel11.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 230, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel12.setText("WIFI :");
        jPanel11.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 260, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel13.setText("Habitaciones:");
        jPanel11.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 290, -1, -1));

        habitacionesAlquiler.setText("jTextField1");
        jPanel11.add(habitacionesAlquiler, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 290, 220, -1));

        jLabel14.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel14.setText("Baños:");
        jPanel11.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 320, -1, -1));

        jLabel15.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel15.setText("Nombre ubicacion: ");
        jPanel11.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 50, -1, -1));

        nombreAlquiler.setText("jTextField1");
        jPanel11.add(nombreAlquiler, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 60, 310, 40));

        jLabel17.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(153, 153, 153));
        jLabel17.setText("Direccion");
        jPanel11.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 110, -1, -1));

        jLabel18.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(153, 153, 153));
        jLabel18.setText("Para conocer el precio total de la reserva le pondremos precio a un dia.");
        jPanel11.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, -1, -1));

        jLabel25.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(153, 153, 153));
        jLabel25.setText("Al hacer esto se calculara el numero de dias que que se quedara el alquilado");
        jPanel11.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 540, -1, -1));

        jButton5.setText("Subir imagen");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 200, 40));

        crearAlquiler.setText("Crear");
        crearAlquiler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearAlquilerActionPerformed(evt);
            }
        });
        jPanel11.add(crearAlquiler, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 380, 300, 90));

        jLabel16.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel16.setText("Baños:");
        jPanel11.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 320, -1, -1));

        bañosAlquiler.setText("jTextField1");
        jPanel11.add(bañosAlquiler, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 320, 220, -1));
        jPanel11.add(wifiAlquiler, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 260, -1, -1));
        jPanel11.add(piscinaAlquiler, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 230, -1, -1));

        registro.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 1510, 610));

        Panel_General.add(registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 190, 1950, 890));

        imagen.setBackground(new java.awt.Color(33, 40, 42));
        imagen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/book4fun/imagenes/Logo BOOK4U.png"))); // NOI18N
        imagen.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 950, 220));

        Panel_General.add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 2, 1940, 190));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel_General, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel_General, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botonCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCreditosActionPerformed
        
        
        if(entrado == true){
            entrado = false;
            panelCreditos.setVisible(true);
        } else { 
            panelCreditos.setVisible(false);
            entrado = true; 
        }
        
    }//GEN-LAST:event_botonCreditosActionPerformed

    private void boton100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton100ActionPerformed
       inputDinero.setText("100");
    }//GEN-LAST:event_boton100ActionPerformed

    private void transferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferenciaActionPerformed
        
        String textoInputDinero = inputDinero.getText();
        int valorDinero = Integer.parseInt(textoInputDinero);
        
        if (valorDinero % 10 == 0) {
            
            try {
                String sql = "UPDATE USUARIOS SET creditos = ? WHERE id = ?";

                PreparedStatement statement = BD.makeConnection().prepareStatement(sql);

            // Define el valor que deseas actualizar usando la variable
                 statement.setInt(1, creditos+(valorDinero/10));
                 statement.setInt(2, BD.comprobarUsuario().getId());

            // Ejecuta la actualización
                int filasActualizadas = statement.executeUpdate();

                if (filasActualizadas > 0) {
                    System.out.println("Actualización exitosa. Filas actualizadas: " + filasActualizadas);
                    panelTransRealizada.setVisible(true);
                    transferencia.setVisible(false);
                    boton100.setVisible(false);
                    boton30.setVisible(false);
                    boton50.setVisible(false);
                    boton10.setVisible(false);
                    creditos += valorDinero/10;
                    nCreditos.setText(String.valueOf(creditos));

                } else {
                    System.out.println("Ninguna fila fue actualizada.");
            }   
            } catch (SQLException e) {e.printStackTrace();}

     
        } else {
            
            panelNoPosible.setVisible(true);
            transferencia.setVisible(false);
            boton100.setVisible(false);
            boton30.setVisible(false);
            boton50.setVisible(false);
            boton10.setVisible(false);

        }
        
    }//GEN-LAST:event_transferenciaActionPerformed

    private void boton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton30ActionPerformed
       inputDinero.setText("30");
    }//GEN-LAST:event_boton30ActionPerformed

    private void boton50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton50ActionPerformed
       inputDinero.setText("50");
    }//GEN-LAST:event_boton50ActionPerformed

    private void boton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton10ActionPerformed
       inputDinero.setText("10");
    }//GEN-LAST:event_boton10ActionPerformed

    private void inputDineroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputDineroActionPerformed
        
    }//GEN-LAST:event_inputDineroActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        panelNoPosible.setVisible(false);
        transferencia.setVisible(true);
        boton100.setVisible(true);
        boton30.setVisible(true);
        boton50.setVisible(true);
        boton10.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        panelTransRealizada.setVisible(false);
        transferencia.setVisible(true);
        boton100.setVisible(true);
        boton30.setVisible(true);
        boton50.setVisible(true);
        boton10.setVisible(true);
  
    }//GEN-LAST:event_jButton2ActionPerformed

    private void crearAlquilerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearAlquilerActionPerformed
       
        
        if (nombreAlquiler.getText().length() != 0 && direccionAlquiler.getText().length() != 0 && nombreDueñoAlquiler.getText().length() != 0 
            && localizacionAlquiler.getText().length() != 0 && metrosAlquiler.getText().length() != 0 && habitacionesAlquiler.getText().length() != 0 
            && tipoAlquiler.getText().length() != 0 && tipoAlquiler.getText().length() != 0 && precioAlquilerDia.getText().length() != 0) {
            
            int piscina = 0;
            int wifi = 0;

            if(wifiAlquiler.isSelected()){ wifi = 1; }
            if(piscinaAlquiler.isSelected()){ piscina = 1; }
            
            String sql = "INSERT INTO VIVIENDA (ID ,ID_USUARIO, NOMBRE, DIRECCION, LOCALIZACION, TIPO, M2, PISCINA, WIFI, HABITACIONES, BAÑOS, PRECIO_DIA) VALUES (ID_VIVIENDA.NEXTVAL, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
            try (Connection conn = BD.makeConnection();
                 PreparedStatement statement = conn.prepareStatement(sql)) {
                statement.setInt(1, BD.comprobarUsuario().getId()); // Reemplaza con el valor correcto para ID_USUARIO
                statement.setString(2, nombreAlquiler.getText()); // Reemplaza con el valor correcto para NOMBRE
                statement.setString(3, direccionAlquiler.getText()); // Reemplaza con el valor correcto para DIRECCION
                statement.setString(4, localizacionAlquiler.getText()); // Reemplaza con el valor correcto para LOCALIZACION
                statement.setString(5, tipoAlquiler.getText()); // Reemplaza con el valor correcto para TIPO
                statement.setInt(6, Integer.parseInt(metrosAlquiler.getText()) ); // Reemplaza con el valor correcto para M2
                statement.setInt(7, piscina); // Reemplaza con el valor correcto para PISCINA
                statement.setInt(8, wifi); // Reemplaza con el valor correcto para WIFI
                statement.setInt(9, Integer.parseInt(habitacionesAlquiler.getText())); 
                statement.setInt(10, Integer.parseInt(bañosAlquiler.getText())); 
                statement.setInt(11, Integer.parseInt(precioAlquilerDia.getText())); 

                int filasAfectadas = statement.executeUpdate();

                if (filasAfectadas > 0) {
                    System.out.println("Inserción exitosa. Filas insertadas: " + filasAfectadas);
                } else {
                    System.out.println("No se insertaron filas.");
                }
            } catch (SQLException e) {e.printStackTrace();}


            
        } else {
        
            
        
        }
        
        
    }//GEN-LAST:event_crearAlquilerActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreacionAlquiler().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_General;
    private javax.swing.JPanel Raya_verde1;
    private javax.swing.JPanel SideBar;
    private javax.swing.JTextField bañosAlquiler;
    private javax.swing.JButton boton10;
    private javax.swing.JButton boton100;
    private javax.swing.JButton boton30;
    private javax.swing.JButton boton50;
    private javax.swing.JButton botonCreditos;
    private javax.swing.JLabel buscador1;
    private javax.swing.JButton crearAlquiler;
    private javax.swing.JTextField direccionAlquiler;
    private javax.swing.JLabel favoritos;
    private javax.swing.JPanel filtro;
    private javax.swing.JTextField habitacionesAlquiler;
    private javax.swing.JPanel imagen;
    private javax.swing.JTextField inputDinero;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lista;
    private javax.swing.JTextField localizacionAlquiler;
    private javax.swing.JTextField metrosAlquiler;
    private javax.swing.JLabel nCreditos;
    private javax.swing.JLabel nCreditos1;
    private javax.swing.JTextField nombreAlquiler;
    private javax.swing.JTextField nombreDueñoAlquiler;
    private javax.swing.JPanel panelCreditos;
    private javax.swing.JPanel panelNoPosible;
    private javax.swing.JPanel panelNoTransRealizada;
    private javax.swing.JPanel panelTransRealizada;
    private javax.swing.JCheckBox piscinaAlquiler;
    private javax.swing.JTextField precioAlquilerDia;
    private javax.swing.JPanel registro;
    private javax.swing.JPanel registro1;
    private javax.swing.JTextField tipoAlquiler;
    private javax.swing.JButton transferencia;
    private javax.swing.JLabel txtIngresarDinero;
    private javax.swing.JCheckBox wifiAlquiler;
    // End of variables declaration//GEN-END:variables
}
